services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: mc-server
    ports:
      - "25565:25565"
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: "${API_KEY}"
      CF_PAGE_URL: "{MODPACK_URL}"
      CF_FORCE_SYNCHRONIZE: "true"
      EULA: "TRUE"
      MEMORY: 12G # Set the maximum memory allocation for the Minecraft server
    volumes:
      - ./data:/data
    restart: unless-stopped